pluginGroup = dev.benjaminor.fluentquery
pluginName = Spring Fluent Query
pluginId = dev.benjaminor.fluentquery
pluginVersion = 0.1.0-SNAPSHOT

# Compatible with IntelliJ IDEA 2024.3+
pluginSinceBuild = 243

platformType = IC
platformVersion = 2024.3.6

gradleVersion = 9.1.0

# Opt-out of bundling Kotlin stdlib (we use Java)
kotlin.stdlib.default.dependency = false

org.gradle.configuration-cache = true
org.gradle.caching = true
